development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: musicmind_test
  pool: 5
  username: joshuachestang
  password: secret
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: musicmind_1_production
  pool: 5
  host: localhost
  username: musicmind_josh
  password: secret
