development:
  adapter: postgresql
  encoding: unicode
  database: musicmind_development
  pool: 5
  username: joshuachestang
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: musicmind_test
  pool: 5
  username: joshuachestang
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: musicmind_1_production
  pool: 5
  host: localhost
  username: musicmind_josh
  password: secret
