require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlbumTracksController do

  # This should return the minimal set of attributes required to create a valid
  # AlbumTrack. As you add validations to AlbumTrack, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlbumTracksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all album_tracks as @album_tracks" do
      album_track = AlbumTrack.create! valid_attributes
      get :index, {}, valid_session
      assigns(:album_tracks).should eq([album_track])
    end
  end

  describe "GET show" do
    it "assigns the requested album_track as @album_track" do
      album_track = AlbumTrack.create! valid_attributes
      get :show, {:id => album_track.to_param}, valid_session
      assigns(:album_track).should eq(album_track)
    end
  end

  describe "GET new" do
    it "assigns a new album_track as @album_track" do
      get :new, {}, valid_session
      assigns(:album_track).should be_a_new(AlbumTrack)
    end
  end

  describe "GET edit" do
    it "assigns the requested album_track as @album_track" do
      album_track = AlbumTrack.create! valid_attributes
      get :edit, {:id => album_track.to_param}, valid_session
      assigns(:album_track).should eq(album_track)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlbumTrack" do
        expect {
          post :create, {:album_track => valid_attributes}, valid_session
        }.to change(AlbumTrack, :count).by(1)
      end

      it "assigns a newly created album_track as @album_track" do
        post :create, {:album_track => valid_attributes}, valid_session
        assigns(:album_track).should be_a(AlbumTrack)
        assigns(:album_track).should be_persisted
      end

      it "redirects to the created album_track" do
        post :create, {:album_track => valid_attributes}, valid_session
        response.should redirect_to(AlbumTrack.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved album_track as @album_track" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumTrack.any_instance.stub(:save).and_return(false)
        post :create, {:album_track => {}}, valid_session
        assigns(:album_track).should be_a_new(AlbumTrack)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumTrack.any_instance.stub(:save).and_return(false)
        post :create, {:album_track => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested album_track" do
        album_track = AlbumTrack.create! valid_attributes
        # Assuming there are no other album_tracks in the database, this
        # specifies that the AlbumTrack created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlbumTrack.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => album_track.to_param, :album_track => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested album_track as @album_track" do
        album_track = AlbumTrack.create! valid_attributes
        put :update, {:id => album_track.to_param, :album_track => valid_attributes}, valid_session
        assigns(:album_track).should eq(album_track)
      end

      it "redirects to the album_track" do
        album_track = AlbumTrack.create! valid_attributes
        put :update, {:id => album_track.to_param, :album_track => valid_attributes}, valid_session
        response.should redirect_to(album_track)
      end
    end

    describe "with invalid params" do
      it "assigns the album_track as @album_track" do
        album_track = AlbumTrack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumTrack.any_instance.stub(:save).and_return(false)
        put :update, {:id => album_track.to_param, :album_track => {}}, valid_session
        assigns(:album_track).should eq(album_track)
      end

      it "re-renders the 'edit' template" do
        album_track = AlbumTrack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumTrack.any_instance.stub(:save).and_return(false)
        put :update, {:id => album_track.to_param, :album_track => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested album_track" do
      album_track = AlbumTrack.create! valid_attributes
      expect {
        delete :destroy, {:id => album_track.to_param}, valid_session
      }.to change(AlbumTrack, :count).by(-1)
    end

    it "redirects to the album_tracks list" do
      album_track = AlbumTrack.create! valid_attributes
      delete :destroy, {:id => album_track.to_param}, valid_session
      response.should redirect_to(album_tracks_url)
    end
  end

end
