require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MasterSongsController do

  # This should return the minimal set of attributes required to create a valid
  # MasterSong. As you add validations to MasterSong, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all master_songs as @master_songs" do
      master_song = MasterSong.create! valid_attributes
      get :index
      assigns(:master_songs).should eq([master_song])
    end
  end

  describe "GET show" do
    it "assigns the requested master_song as @master_song" do
      master_song = MasterSong.create! valid_attributes
      get :show, :id => master_song.id.to_s
      assigns(:master_song).should eq(master_song)
    end
  end

  describe "GET new" do
    it "assigns a new master_song as @master_song" do
      get :new
      assigns(:master_song).should be_a_new(MasterSong)
    end
  end

  describe "GET edit" do
    it "assigns the requested master_song as @master_song" do
      master_song = MasterSong.create! valid_attributes
      get :edit, :id => master_song.id.to_s
      assigns(:master_song).should eq(master_song)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MasterSong" do
        expect {
          post :create, :master_song => valid_attributes
        }.to change(MasterSong, :count).by(1)
      end

      it "assigns a newly created master_song as @master_song" do
        post :create, :master_song => valid_attributes
        assigns(:master_song).should be_a(MasterSong)
        assigns(:master_song).should be_persisted
      end

      it "redirects to the created master_song" do
        post :create, :master_song => valid_attributes
        response.should redirect_to(MasterSong.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved master_song as @master_song" do
        # Trigger the behavior that occurs when invalid params are submitted
        MasterSong.any_instance.stub(:save).and_return(false)
        post :create, :master_song => {}
        assigns(:master_song).should be_a_new(MasterSong)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MasterSong.any_instance.stub(:save).and_return(false)
        post :create, :master_song => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested master_song" do
        master_song = MasterSong.create! valid_attributes
        # Assuming there are no other master_songs in the database, this
        # specifies that the MasterSong created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MasterSong.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => master_song.id, :master_song => {'these' => 'params'}
      end

      it "assigns the requested master_song as @master_song" do
        master_song = MasterSong.create! valid_attributes
        put :update, :id => master_song.id, :master_song => valid_attributes
        assigns(:master_song).should eq(master_song)
      end

      it "redirects to the master_song" do
        master_song = MasterSong.create! valid_attributes
        put :update, :id => master_song.id, :master_song => valid_attributes
        response.should redirect_to(master_song)
      end
    end

    describe "with invalid params" do
      it "assigns the master_song as @master_song" do
        master_song = MasterSong.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MasterSong.any_instance.stub(:save).and_return(false)
        put :update, :id => master_song.id.to_s, :master_song => {}
        assigns(:master_song).should eq(master_song)
      end

      it "re-renders the 'edit' template" do
        master_song = MasterSong.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MasterSong.any_instance.stub(:save).and_return(false)
        put :update, :id => master_song.id.to_s, :master_song => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested master_song" do
      master_song = MasterSong.create! valid_attributes
      expect {
        delete :destroy, :id => master_song.id.to_s
      }.to change(MasterSong, :count).by(-1)
    end

    it "redirects to the master_songs list" do
      master_song = MasterSong.create! valid_attributes
      delete :destroy, :id => master_song.id.to_s
      response.should redirect_to(master_songs_url)
    end
  end

end
