require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SongUpVotesController do

  # This should return the minimal set of attributes required to create a valid
  # SongUpVote. As you add validations to SongUpVote, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SongUpVotesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all song_up_votes as @song_up_votes" do
      song_up_vote = SongUpVote.create! valid_attributes
      get :index, {}, valid_session
      assigns(:song_up_votes).should eq([song_up_vote])
    end
  end

  describe "GET show" do
    it "assigns the requested song_up_vote as @song_up_vote" do
      song_up_vote = SongUpVote.create! valid_attributes
      get :show, {:id => song_up_vote.to_param}, valid_session
      assigns(:song_up_vote).should eq(song_up_vote)
    end
  end

  describe "GET new" do
    it "assigns a new song_up_vote as @song_up_vote" do
      get :new, {}, valid_session
      assigns(:song_up_vote).should be_a_new(SongUpVote)
    end
  end

  describe "GET edit" do
    it "assigns the requested song_up_vote as @song_up_vote" do
      song_up_vote = SongUpVote.create! valid_attributes
      get :edit, {:id => song_up_vote.to_param}, valid_session
      assigns(:song_up_vote).should eq(song_up_vote)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SongUpVote" do
        expect {
          post :create, {:song_up_vote => valid_attributes}, valid_session
        }.to change(SongUpVote, :count).by(1)
      end

      it "assigns a newly created song_up_vote as @song_up_vote" do
        post :create, {:song_up_vote => valid_attributes}, valid_session
        assigns(:song_up_vote).should be_a(SongUpVote)
        assigns(:song_up_vote).should be_persisted
      end

      it "redirects to the created song_up_vote" do
        post :create, {:song_up_vote => valid_attributes}, valid_session
        response.should redirect_to(SongUpVote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved song_up_vote as @song_up_vote" do
        # Trigger the behavior that occurs when invalid params are submitted
        SongUpVote.any_instance.stub(:save).and_return(false)
        post :create, {:song_up_vote => {}}, valid_session
        assigns(:song_up_vote).should be_a_new(SongUpVote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SongUpVote.any_instance.stub(:save).and_return(false)
        post :create, {:song_up_vote => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested song_up_vote" do
        song_up_vote = SongUpVote.create! valid_attributes
        # Assuming there are no other song_up_votes in the database, this
        # specifies that the SongUpVote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SongUpVote.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => song_up_vote.to_param, :song_up_vote => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested song_up_vote as @song_up_vote" do
        song_up_vote = SongUpVote.create! valid_attributes
        put :update, {:id => song_up_vote.to_param, :song_up_vote => valid_attributes}, valid_session
        assigns(:song_up_vote).should eq(song_up_vote)
      end

      it "redirects to the song_up_vote" do
        song_up_vote = SongUpVote.create! valid_attributes
        put :update, {:id => song_up_vote.to_param, :song_up_vote => valid_attributes}, valid_session
        response.should redirect_to(song_up_vote)
      end
    end

    describe "with invalid params" do
      it "assigns the song_up_vote as @song_up_vote" do
        song_up_vote = SongUpVote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SongUpVote.any_instance.stub(:save).and_return(false)
        put :update, {:id => song_up_vote.to_param, :song_up_vote => {}}, valid_session
        assigns(:song_up_vote).should eq(song_up_vote)
      end

      it "re-renders the 'edit' template" do
        song_up_vote = SongUpVote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SongUpVote.any_instance.stub(:save).and_return(false)
        put :update, {:id => song_up_vote.to_param, :song_up_vote => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested song_up_vote" do
      song_up_vote = SongUpVote.create! valid_attributes
      expect {
        delete :destroy, {:id => song_up_vote.to_param}, valid_session
      }.to change(SongUpVote, :count).by(-1)
    end

    it "redirects to the song_up_votes list" do
      song_up_vote = SongUpVote.create! valid_attributes
      delete :destroy, {:id => song_up_vote.to_param}, valid_session
      response.should redirect_to(song_up_votes_url)
    end
  end

end
