require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserSongUploadsController do

  # This should return the minimal set of attributes required to create a valid
  # UserSongUpload. As you add validations to UserSongUpload, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all user_song_uploads as @user_song_uploads" do
      user_song_upload = UserSongUpload.create! valid_attributes
      get :index
      assigns(:user_song_uploads).should eq([user_song_upload])
    end
  end

  describe "GET show" do
    it "assigns the requested user_song_upload as @user_song_upload" do
      user_song_upload = UserSongUpload.create! valid_attributes
      get :show, :id => user_song_upload.id.to_s
      assigns(:user_song_upload).should eq(user_song_upload)
    end
  end

  describe "GET new" do
    it "assigns a new user_song_upload as @user_song_upload" do
      get :new
      assigns(:user_song_upload).should be_a_new(UserSongUpload)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_song_upload as @user_song_upload" do
      user_song_upload = UserSongUpload.create! valid_attributes
      get :edit, :id => user_song_upload.id.to_s
      assigns(:user_song_upload).should eq(user_song_upload)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserSongUpload" do
        expect {
          post :create, :user_song_upload => valid_attributes
        }.to change(UserSongUpload, :count).by(1)
      end

      it "assigns a newly created user_song_upload as @user_song_upload" do
        post :create, :user_song_upload => valid_attributes
        assigns(:user_song_upload).should be_a(UserSongUpload)
        assigns(:user_song_upload).should be_persisted
      end

      it "redirects to the created user_song_upload" do
        post :create, :user_song_upload => valid_attributes
        response.should redirect_to(UserSongUpload.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_song_upload as @user_song_upload" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserSongUpload.any_instance.stub(:save).and_return(false)
        post :create, :user_song_upload => {}
        assigns(:user_song_upload).should be_a_new(UserSongUpload)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserSongUpload.any_instance.stub(:save).and_return(false)
        post :create, :user_song_upload => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_song_upload" do
        user_song_upload = UserSongUpload.create! valid_attributes
        # Assuming there are no other user_song_uploads in the database, this
        # specifies that the UserSongUpload created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserSongUpload.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => user_song_upload.id, :user_song_upload => {'these' => 'params'}
      end

      it "assigns the requested user_song_upload as @user_song_upload" do
        user_song_upload = UserSongUpload.create! valid_attributes
        put :update, :id => user_song_upload.id, :user_song_upload => valid_attributes
        assigns(:user_song_upload).should eq(user_song_upload)
      end

      it "redirects to the user_song_upload" do
        user_song_upload = UserSongUpload.create! valid_attributes
        put :update, :id => user_song_upload.id, :user_song_upload => valid_attributes
        response.should redirect_to(user_song_upload)
      end
    end

    describe "with invalid params" do
      it "assigns the user_song_upload as @user_song_upload" do
        user_song_upload = UserSongUpload.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserSongUpload.any_instance.stub(:save).and_return(false)
        put :update, :id => user_song_upload.id.to_s, :user_song_upload => {}
        assigns(:user_song_upload).should eq(user_song_upload)
      end

      it "re-renders the 'edit' template" do
        user_song_upload = UserSongUpload.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserSongUpload.any_instance.stub(:save).and_return(false)
        put :update, :id => user_song_upload.id.to_s, :user_song_upload => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_song_upload" do
      user_song_upload = UserSongUpload.create! valid_attributes
      expect {
        delete :destroy, :id => user_song_upload.id.to_s
      }.to change(UserSongUpload, :count).by(-1)
    end

    it "redirects to the user_song_uploads list" do
      user_song_upload = UserSongUpload.create! valid_attributes
      delete :destroy, :id => user_song_upload.id.to_s
      response.should redirect_to(user_song_uploads_url)
    end
  end

end
